INHALATOR_SERVICE_NAME = "inhalator.service"
INHALATOR_REPO_FOLDER_PATH = "/home/pi/Inhalator"
# TODO: replace with "scripts/rpi_scripts"
RPI_INIT_SCRIPTS_FOLDER = "rasp_init"
RPI_SCRIPTS_FOLDER = "scripts"
